# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev24+ga12288d.d20230701'
__version_tuple__ = version_tuple = (0, 1, 'dev24', 'ga12288d.d20230701')
