# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.1.dev26+g3530fe2.d20230703'
__version_tuple__ = version_tuple = (0, 1, 'dev26', 'g3530fe2.d20230703')
