version: "3"
services:
  vision:
    container_name: vision
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8888:8888"
      - "6006:6006"
    volumes:
      - ../:/workspace
      # Uncomment the following line to enable X11 forwarding
      # - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    restart: always
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: 1
