version: "3"
services:
  deepx:
    container_name: deepx
    build:
      context: .
      dockerfile: Dockerfile
    # image: ksterx/ai:ubuntu-0.1
    shm_size: '16gb'
    ports:
      - "5000:5000"
      - "8080:8080"
      - "8888:8888"
      - "6006:6006"
      - "2525:2525"
    volumes:
      - ../:/workspace
      # Uncomment the following line to enable X11 forwarding
      # - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=$DISPLAY
    restart: always
    tty: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
              count: 1
    working_dir: /workspace
