# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.1.dev10+g4a3c18a.d20230716'
__version_tuple__ = version_tuple = (1, 0, 1, 'dev10', 'g4a3c18a.d20230716')
