# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '1.0.3.dev11+g108735c.d20230804'
__version_tuple__ = version_tuple = (1, 0, 3, 'dev11', 'g108735c.d20230804')
